app = "codelive2025"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "2150"
  NODE_ENV = "production"

[http_service]
  internal_port = 2150
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  protocol = "http"

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 